
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author RPL
 */
public class DataSiswa extends javax.swing.JFrame {
    Connection koneksi;
    String id = "";
    /**
     * Creates new form DataSiswa
     */
    public DataSiswa() {
        initComponents();
        koneksi();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nm_kolom = new javax.swing.JTextField();
        almt_kolom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cowo = new javax.swing.JRadioButton();
        cewe = new javax.swing.JRadioButton();
        pilihan = new javax.swing.JComboBox<>();
        sklh_kolom = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Pendaftaran Siswa Baru");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));
        getContentPane().add(nm_kolom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 210, -1));
        getContentPane().add(almt_kolom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 210, 100));

        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel5.setText("Agama");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel6.setText("Sekolah Asal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        buttonGroup1.add(cowo);
        cowo.setText("laki-laki");
        getContentPane().add(cowo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        buttonGroup1.add(cewe);
        cewe.setText("perempuan");
        getContentPane().add(cewe, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        pilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "islam", "kristen", "katholik", "hindu", "budha" }));
        getContentPane().add(pilihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 210, -1));
        getContentPane().add(sklh_kolom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 210, -1));

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Alamat", "Jenis Kelamin", "Agama", "Sekolah Asal"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 630, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        if(id == "") {
            create();
        } else {
            update();
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        edit();
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        delete();
    }//GEN-LAST:event_hapusActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clear();
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField almt_kolom;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cewe;
    private javax.swing.JButton clear;
    private javax.swing.JRadioButton cowo;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nm_kolom;
    private javax.swing.JComboBox<String> pilihan;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField sklh_kolom;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

    private void koneksi() {
        try {
            String server = "jdbc:mysql://localhost:3306/db_onnypendaftaran";
            String user = "root";
            String pass = "";
            
            DriverManager.registerDriver(new com.mysql.cj.jdbc.Driver());
            koneksi = DriverManager.getConnection(server, user, pass);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void tampil() {
        DefaultTableModel data = (DefaultTableModel) tabel.getModel();
        data.setRowCount(0);
        
        try {
            String sql = "SELECT * FROM tb_siswa";
            ResultSet res = koneksi.createStatement().executeQuery(sql);
            
            while(res.next()) {
                data.addRow(new Object[] {
                    res.getString(1), res.getString(2),
                    res.getString(3), res.getString(4),
                    res.getString(5), res.getString(6)
                });
            }
            tabel.setModel(data);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void create() {
        String jk = (cowo.isSelected()) ? "laki-laki" : "perempuan";
        String sql = "INSERT INTO tb_siswa VALUES(null,"
                + "'" + nm_kolom.getText() + "',"
                + "'" + almt_kolom.getText() + "',"
                + "'" + jk + "',"
                + "'" + pilihan.getSelectedItem().toString() + "',"
                + "'" + sklh_kolom.getText() + "')";
        
        try {
            int res = koneksi.createStatement().executeUpdate(sql);
            if (res > -1) {
                tampil();
                nm_kolom.setText("");
                almt_kolom.setText("");
                cowo.setSelected(false);
                cewe.setSelected(false);
                pilihan.setSelectedIndex(0);
                sklh_kolom.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void delete() {
        int row = tabel.getSelectedRow();
        String id = tabel.getValueAt(row, 0).toString();
        
        try {
            String sql = "DELETE FROM tb_siswa WHERE id="+id;
            int res = koneksi.createStatement().executeUpdate(sql);
            
            if(res > -1) {
                tampil();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void edit() {
        int row = tabel.getSelectedRow();
        String id_siswa = tabel.getValueAt(row, 0).toString();
        
        try {
            String sql = "SELECT * FROM tb_siswa WHERE id="+id_siswa;
            ResultSet res = koneksi.createStatement().executeQuery(sql);
            
            while(res.next()) {
                id = res.getString(1);
                nm_kolom.setText(res.getString(2));
                almt_kolom.setText(res.getString(3));
                if(res.getString(4) == "laki-laki") {
                    cowo.setSelected(true);
                } else {
                    cewe.setSelected(true);
                }
                pilihan.setSelectedItem(res.getString(5));
                sklh_kolom.setText(res.getString(6));
                edit.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void clear() {
        id = null;
        nm_kolom.setText("");
        almt_kolom.setText("");
        cowo.setSelected(false);
        cewe.setSelected(false);
        pilihan.setSelectedIndex(0);
        sklh_kolom.setText("");
        edit.setEnabled(true);
    }
    
    private void update() {
        String jk = (cowo.isSelected()) ? "laki-laki" : "perempuan";
        String sql = "UPDATE tb_siswa SET "
                + "nama = '" + nm_kolom.getText() + "',"
                + "alamat = '" + almt_kolom.getText() + "',"
                + "jenis_kelamin = '" + jk + "',"
                + "agama = '" + pilihan.getSelectedItem().toString() + "',"
                + "sekolah_asal = '" + sklh_kolom.getText() + "' "
                + "WHERE id = "+id;
        
        try {
            int res = koneksi.createStatement().executeUpdate(sql);
            if (res > -1) {
                tampil();
                clear();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }


}
